Python Basics

# Python Basics

## Python Basics

In [ ]:
keyboard shortcuts

a - to create a cell above any selected cell
b - to create a cell below any selected cell
dd - to delete a selected cell 
Esc + m - to convert a cell to markdown

In [2]:
12+23+89+78  # shift + enter to execute codes

202

In [4]:
12+23+89+78
+98+78+42

# One instruction in mutltiple lines - only last line is printed

218

In [7]:
# Line continuation operator
# multiline comments -  use ctrl + /
# addition of numbers - operation
# spead in multiple lines

12+23+89+78\
+98+78+42

420

In [8]:
(12+23+89+78
+98+78+42)

420

In [9]:
[12+23+89+78
+98+78+42]

[420]

In [10]:
{12+23+89+78
+98+78+42}

{420}

## Assignment Operation

In [11]:
x = 2

In [12]:
x = x + 2

In [14]:
print(x)  # explicit printing

4


In [15]:
x

4

In [16]:
y = 5

In [17]:
x
y

5

In [18]:
print(x)
print(y)

4
5


In [ ]:
Identifier naming convention

1. case sensitive
2. may start from small/capital alphabets or an underscore
3. cannt start with numbers
4. dont have to declare explicitly

In [20]:
x = 4
a = b = c = 'Python'  # text(string) values are specified within single(double) quotes
p, q, r = "Shubham", 40, True

s = 15; t = 18; u = 89  # 3(mutiple) instructions in one line

In [21]:
print(x, a, b, c, p, q, r, s, t, u)

4 Python Python Python Shubham 40 True 15 18 89


In [22]:
print('Shubham', 'Pandey')

Shubham Pandey


In [23]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [24]:
print('Shubham', 'Pandey', sep = '')

ShubhamPandey


In [ ]:
To get the documentation popped up - keep your cursor with in parenthesis and hit  - shift + tab

### Basic Data Types

In [25]:
a = 5          # int
b = 5.0        # float
c = 4 + 1j     # complex
d = 'hello'    # str
e = False      # boolean

In [26]:
type(a)

int

## Arithmetic Operators

In [29]:
23 + 67  # addition

90

In [30]:
'shubham' + 'pandey'  # concatenation

'shubhampandey'

In [31]:
2*3

6

In [32]:
'a'*6

'aaaaaa'

In [34]:
12%5

2

In [ ]:
12

In [35]:
12//5

2

In [ ]:
+   ---  addition/concatenation
-   ---  subtraction
*
/
%   ---  modulus operator - remainder
//  ---  integer division or floor division or quotient
**  ---  exponentiation

In [36]:
2**5

32

In [37]:
pow(2,5)

32

In [38]:
var = 'I have savings for the month as ' + 2300

TypeError: can only concatenate str (not "int") to str

In [39]:
var = 'I have savings for the month as ' + str(2300)

In [40]:
var

'I have savings for the month as 2300'

In [41]:
int(True)

1

In [42]:
int(False)

0

## Data structures

In [ ]:
1. list - a mutable ordered collection of hetrogenous/homogenous items
2. tuple - a immutable ordered collection of hetrogenous/homogenous items
3. set - a mutable unordered collection of unique hetrogenous/homogenous items
4. dictionary
5. array
6. series
7. dataframe

In [43]:
tpp = 20, True, 'new', 34.8, 89

In [44]:
tpp

(20, True, 'new', 34.8, 89)

In [45]:
type(tpp)

tuple

In [46]:
lst = [20, True, 'new', 34.8, 89]

In [47]:
type(lst)

list

In [48]:
sst = {20, True, 'new', 34.8, 89}

In [49]:
type(sst)

set

In [50]:
print(dir(tpp))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [51]:
print(dir(lst))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [52]:
tpp

(20, True, 'new', 34.8, 89)

In [53]:
tpp = 20, True, 'new', 34.8, 89, 89, 'new', 'new', 20

In [54]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 20)

In [55]:
tpp.index(89)

4

In [57]:
tpp.index(89, 0)

4

In [58]:
tpp.index(89, 1)

4

In [59]:
tpp.index(89, 5)

5

In [60]:
tpp.count('new')

3

In [62]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 20)

In [61]:
tpp[0]

20

In [63]:
tpp[-9]

20

In [64]:
len(tpp)

9

In [66]:
tpp[len(tpp)-1]

20

In [67]:
tpp[-1]

20

In [68]:
lst

[20, True, 'new', 34.8, 89]

In [69]:
lst[0]

20

In [70]:
lst[-1]

89

In [71]:
lst[0] = 55

In [72]:
lst

[55, True, 'new', 34.8, 89]

In [73]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 20)

In [74]:
tpp[1] = "True"

TypeError: 'tuple' object does not support item assignment

In [75]:
name = "shubham"

In [76]:
name[0]

's'

In [77]:
name[-1]

'm'

In [78]:
name[0] = 'S'

TypeError: 'str' object does not support item assignment

#### subsetting or slicing

In [79]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 20)

In [ ]:
syntax:
    
tpp[<start>:<stop>:<step size>]

<start> - included
<stop>  - not included

In [80]:
tpp[1:6:1]

(True, 'new', 34.8, 89, 89)

In [81]:
tpp[1:6:2]

(True, 34.8, 89)

In [83]:
tpp[1:7:1]

(True, 'new', 34.8, 89, 89, 'new')

In [85]:
# if we dont provide step size - 1 step is taken by default

tpp[1:7]

(True, 'new', 34.8, 89, 89, 'new')

In [87]:
# if we dont provide start - it starts from the begining - begining depends on step size

tpp[:7:1]

(20, True, 'new', 34.8, 89, 89, 'new')

In [88]:
tpp[:7:-1]

(20,)

In [89]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 20)

In [90]:
tpp = 20, True, 'new', 34.8, 89, 89, 'new', 'new', 78

In [91]:
tpp[:2:-1]

(78, 'new', 'new', 89, 89, 34.8)

In [92]:
tpp

(20, True, 'new', 34.8, 89, 89, 'new', 'new', 78)

In [93]:
# if stop position is not given

tpp[2::2]

('new', 89, 'new', 78)

In [94]:
txt = 'python'

In [95]:
txt[0]

'p'

In [96]:
txt[1:]

'ython'

In [ ]:
Task:
    
Using slicing - reverse the text - Python. The result should be - 'nohtyP'

In [97]:
txt = 'Python'

In [98]:
txt[5::-1]

'nohtyP'

In [99]:
txt[-1::-1]

'nohtyP'

In [100]:
txt[::-1]

'nohtyP'

In [101]:
txt[5:0]

''

### List methods

In [ ]:
Removing items from a list

clear - Remove all items from list
pop - Remove and return item at index (default last)
remove - Remove first occurrence of value

In [104]:
lst = [55, True, 'new', 34.8, 89]

In [105]:
lst.clear()

In [106]:
lst

[]

In [107]:
lst = [55, True, 'new', 34.8, 89]

In [108]:
lst.pop()

89

In [109]:
lst

[55, True, 'new', 34.8]

In [110]:
lst = [55, True, 'new', 34.8, 89]

In [111]:
lst.pop(2)

'new'

In [112]:
lst

[55, True, 34.8, 89]

In [113]:
lst = [55, True, 'new', 34.8, 89]

In [116]:
?lst.remove

Signature: lst.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [117]:
lst.remove('new')

In [118]:
lst

[55, True, 34.8, 89]

In [120]:
lst1 = [55, True, 34.8, 89, [55, True, 34.8, 89]]

In [122]:
lst1[-1].remove(89)

In [ ]:
Adding items to a list

Append - Append object to the end of the list
extend - Extend list by appending elements from the iterable
insert - Insert object before index

In [123]:
lst

[55, True, 34.8, 89]

In [124]:
?lst.append

Signature: lst.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method


In [126]:
lst.append(78)

In [127]:
lst

[55, True, 34.8, 89, 78]

In [128]:
?lst.extend

Signature: lst.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method


In [129]:
lst.extend(34)

TypeError: 'int' object is not iterable

In [130]:
lst.extend('text')

In [131]:
lst

[55, True, 34.8, 89, 78, 't', 'e', 'x', 't']

In [133]:
lst.insert(1,'True')

In [134]:
lst

[55, 'True', True, 34.8, 89, 78, 't', 'e', 'x', 't']

In [ ]:
Ordering items

sort
reverse

In [135]:
lst = [2,3,45,67,89,34,23]

In [136]:
lst.sort()

In [137]:
lst

[2, 3, 23, 34, 45, 67, 89]

In [142]:
lst.sort(reverse=True)

In [143]:
lst

[89, 67, 45, 34, 23, 3, 2]

In [144]:
?lst.reverse

Signature: lst.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method


In [145]:
lst.reverse()

In [146]:
lst

[2, 3, 23, 34, 45, 67, 89]

In [147]:
lst1 = ['a', 'b', 'c', 'd']

In [149]:
new_lst1 = lst1

In [150]:
lst1[1] = 'bbbb'

In [151]:
lst1

['a', 'bbbb', 'c', 'd']

In [152]:
new_lst1

['a', 'bbbb', 'c', 'd']

In [159]:
lst1 = ['a', 'b', 'c', 'd']

In [158]:
new_lst1 = lst1.copy()

In [160]:
lst1[1] = 'bbbb'

In [161]:
new_lst1

['a', 'b', 'c', 'd']

## working with sets

In [162]:
sst = {12,'item1', True, 12, 'item2'}

In [163]:
print(dir(sst))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [ ]:
??? Which functions are not present here in sets which are present in tuple as well as list???

In [ ]:
count
index

In [164]:
sst

{12, True, 'item1', 'item2'}

In [ ]:
a set cannot have duplicates

In [ ]:
set is unordered - no specific position(index) is decided for items

In [165]:
set1 = {'a', 'b', 'c', 'd'}

In [166]:
set1.clear()

In [167]:
set1

set()

In [170]:
type([])  # empty list

list

In [172]:
type(())  # empty tuple

tuple

In [174]:
type(set())  # empty set

set

In [175]:
type({})  # empty dictionary

dict

In [2]:
set1 = {'a', 'b', 'c', 'd'}
set2 = {'p', 'q', 'r', 'b', 'd'}

In [178]:
set1.union(set2)

{'a', 'b', 'c', 'd', 'p', 'q', 'r'}

In [179]:
set1.intersection(set2)

{'b', 'd'}

In [180]:
set1.symmetric_difference(set2)

{'a', 'c', 'p', 'q', 'r'}

In [3]:
set1.difference(set2)

{'a', 'c'}

In [4]:
set2.difference(set1)

{'p', 'q', 'r'}

In [5]:
set1.add('e')

In [6]:
set1

{'a', 'b', 'c', 'd', 'e'}

In [8]:
set1 = {'a', 'b', 'c', 'd'}
set2 = {'p', 'q', 'r', 'b', 'd'}

In [9]:
set2.difference(set1)

{'p', 'q', 'r'}

In [10]:
set2.difference_update(set1)

In [11]:
set1

{'a', 'b', 'c', 'd'}

In [12]:
set2

{'p', 'q', 'r'}

In [13]:
set1 = {'a', 'b', 'c', 'd'}
set2 = {'p', 'q', 'r', 'b', 'd'}

In [14]:
set1.symmetric_difference(set2)

{'a', 'c', 'p', 'q', 'r'}

In [15]:
set1, set2

({'a', 'b', 'c', 'd'}, {'b', 'd', 'p', 'q', 'r'})

In [16]:
set1.symmetric_difference_update(set2)

In [17]:
set1

{'a', 'c', 'p', 'q', 'r'}

In [18]:
set2

{'b', 'd', 'p', 'q', 'r'}

### Dictionary

In [19]:
country = ['a', 'b', 'c']
population = [200, 300, 400]

In [ ]:
population of country 'b'

In [20]:
country.index('b')

1

In [21]:
population[country.index('b')]

300

In [22]:
world = {'a': 200, 'b':300, 'c':400}

In [23]:
world['b']

300

In [24]:
print(dir(world))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [25]:
world.keys()

dict_keys(['a', 'b', 'c'])

In [26]:
world.items()

dict_items([('a', 200), ('b', 300), ('c', 400)])

In [27]:
world.values()

dict_values([200, 300, 400])

In [28]:
world

{'a': 200, 'b': 300, 'c': 400}

In [29]:
world['d'] = 500

In [30]:
world

{'a': 200, 'b': 300, 'c': 400, 'd': 500}

In [31]:
world.update({'e':800})

In [32]:
world

{'a': 200, 'b': 300, 'c': 400, 'd': 500, 'e': 800}

In [33]:
world['b'] = 1000

In [34]:
world

{'a': 200, 'b': 1000, 'c': 400, 'd': 500, 'e': 800}

In [35]:
{'a': 200, 'b': 1000, 'c': 400, 'd': 500, 'e': 800, 'e': 2000}

{'a': 200, 'b': 1000, 'c': 400, 'd': 500, 'e': 2000}

## Loops and conditional statements

In [36]:
height = [175, 180, 165]
weight = [75, 80, 68]

In [ ]:
BMI = ?

In [37]:
weight/pow(height/100,2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [38]:
sales_quarter_2020 = [20,30,40,50]
sales_quarter_2021 = [45,35,34,21]

In [ ]:
I want quarter-wise total for both the years

[20+45, 30+35, 40+34, 50+21]

In [39]:
sales_quarter_2020 + sales_quarter_2021

[20, 30, 40, 50, 45, 35, 34, 21]

In [41]:
sales_quarter_2020[0] + sales_quarter_2021[0]

65

In [42]:
sales_quarter_2020[1] + sales_quarter_2021[1]

65

In [43]:
sales_quarter_2020[2] + sales_quarter_2021[2]

74

In [44]:
for i in [0, 1, 2, 3]:
    print(sales_quarter_2020[i] + sales_quarter_2021[i])

65
65
74
71


In [45]:
range(1,100,2)

range(1, 100, 2)

In [48]:
print(list(range(1,100,5)))

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]


In [49]:
print(list(range(20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [50]:
for i in range(4):
    print(sales_quarter_2020[i] + sales_quarter_2021[i])

65
65
74
71


In [53]:
total = []

for i in range(4):
    
    total.append(sales_quarter_2020[i] + sales_quarter_2021[i])

In [54]:
total

[65, 65, 74, 71]

In [55]:
len(sales_quarter_2020)

4

In [56]:
total = []

for i in range(len(sales_quarter_2020)):
    
    total.append(sales_quarter_2020[i] + sales_quarter_2021[i])

In [ ]:
height = [175, 180, 165]
weight = [75, 80, 68]

In [58]:
BMI = []

for i in range(len(height)):
    
    bmi = weight[i]/pow(height[i]/100,2)
    
    print(bmi)
    
    BMI.append(bmi)

24.489795918367346
24.691358024691358
24.977043158861342


In [59]:
BMI

[24.489795918367346, 24.691358024691358, 24.977043158861342]

In [60]:
names = ['a', 'b', 'c']
height = [175, 180, 165]
weight = [75, 80, 68]

In [ ]:
{'a':24.489, 'b': 24.6, 'c': 24.97}

In [61]:
BMI_dic = {}

for i in range(len(names)):
    
    bmi = weight[i]/pow(height[i]/100,2)
    
    BMI_dic[names[i]] = bmi

In [62]:
BMI_dic

{'a': 24.489795918367346, 'b': 24.691358024691358, 'c': 24.977043158861342}

In [63]:
for i, j in zip(weight,height):
    
    bmi = i/pow(j/100,2)
    
    print(bmi)

24.489795918367346
24.691358024691358
24.977043158861342


In [65]:
for i in [0,1,2]:
    
    print(height[i])

175
180
165


In [66]:
for i in height:
    
    print(i)

175
180
165


In [67]:
for i in 'Python':
    print(i)

P
y
t
h
o
n


In [68]:
height

[175, 180, 165]

In [69]:
[i for i in height]

[175, 180, 165]

In [70]:
[i/2 for i in height]

[87.5, 90.0, 82.5]

In [ ]:
ask

create a list using list comprehension containing cube values of all the even numbers from 1 to 50

In [77]:
cubes = []

for i in range(2,51,2):
    
    c = pow(i, 3)
    
    cubes.append(c)

In [78]:
print(cubes)

[8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000, 10648, 13824, 17576, 21952, 27000, 32768, 39304, 46656, 54872, 64000, 74088, 85184, 97336, 110592, 125000]


In [79]:
[pow(i,3) for i in range(2,51,2)]

[8,
 64,
 216,
 512,
 1000,
 1728,
 2744,
 4096,
 5832,
 8000,
 10648,
 13824,
 17576,
 21952,
 27000,
 32768,
 39304,
 46656,
 54872,
 64000,
 74088,
 85184,
 97336,
 110592,
 125000]

In [80]:
height, weight

([175, 180, 165], [75, 80, 68])

In [82]:
[i/pow(j/100,2) for i, j in zip(weight, height)]

[24.489795918367346, 24.691358024691358, 24.977043158861342]

In [83]:
country, population

(['a', 'b', 'c'], [200, 300, 400])

In [84]:
{c:p for c,p in zip(country, population)}

{'a': 200, 'b': 300, 'c': 400}

In [85]:
dict(zip(country, population))

{'a': 200, 'b': 300, 'c': 400}

In [86]:
names = ['a','b','c']
BMI = [24.489795918367346, 24.691358024691358, 24.977043158861342]

In [87]:
{i:j for i,j in zip(names, BMI)}

{'a': 24.489795918367346, 'b': 24.691358024691358, 'c': 24.977043158861342}

In [88]:
names = ['a', 'b', 'c']
height = [175, 180, 165]
weight = [75, 80, 68]

In [90]:
{n:w/pow(h/100,2) for n,w,h in zip(names,weight,height)}

{'a': 24.489795918367346, 'b': 24.691358024691358, 'c': 24.977043158861342}

In [ ]:
if <condition>:
    <action>
elif <condition>:    
    <action>
elif <condition>:    
    <action>
else:
    <action>

In [ ]:
How to provide conditions?

logical operators

In [ ]:
==   --- whether equal
!=   --- whether not equal
>
<
>=   --- greater than or equal to
<=   --- less than or equal to

in       -- whether contains 
not in   -- whether does not contain

Following operators are used to combine multiple conditions

and
or 
not

For bitwise operation

&  --- and
|  --- or
~  --- not

In [91]:
2==2

True

In [92]:
2!=2

False

In [93]:
(10>5) and (10>6)

True

In [94]:
(10<5) and (10>6)

False

In [95]:
(10<5) and (10<6)

False

In [96]:
(10>5) and (10<6)

False

In [97]:
(10>5) and (10>6), (10<5) and (10>6), (10<5) and (10<6), (10>5) and (10<6)

(True, False, False, False)

In [98]:
(10>5) or (10>6), (10<5) or (10>6), (10<5) or (10<6), (10>5) or (10<6)

(True, True, False, True)

In [ ]:
How to take input from the user?

In [101]:
amt = input("Enter the amount")

Enter the amount 2000


In [ ]:
Task

Create a program which takes input from the user for the transaction amount

provide discount and find net payable under the following condition

if amount is less than 2000 - no discount
for any amount more than or equal to 2000 - 15% discount

In [ ]:
5 mins

In [105]:
amt = float(input("Enter the amount"))

Enter the amount 2500


In [107]:
if amt<2000:
    discount = 0
else:
    discount = amt*.15
    
net_payable = amt - discount

print(net_payable)

2125.0


In [ ]:
Task

Create a program which takes input from the user for the transaction amount

provide discount and find net payable under the following condition

if amount is less than 2000 - no discount
for any amount between 2000 and 5000 - 15% discount (2000 included but 5000 excluded)
for any amount more than or equal to 5000 - 20% discount

In [108]:
if amt<2000:
    discount = 0
elif amt<5000:
    discount = amt*.15
else:
    discount = amt*.20
    
net_payable = amt - discount

print(net_payable)

2125.0


In [ ]:
Use lst and create a program which returns a list with only numbers divisible by 3

In [112]:
lst = [12,23,34,45,67,89,99]

for n in lst:
    
    if n%3 == 0:
        print(n)

12
45
99


In [113]:
lst = [12,23,34,45,67,89,99]

lst_div_3 = []

for n in lst:
    
    if n%3 == 0:
        
        lst_div_3.append(n)

In [114]:
lst_div_3

[12, 45, 99]

In [116]:
[i for i in lst if i%3==0]

[12, 45, 99]

### Create a use defined function

In [117]:
def my_function(a,b,c):
    
    return 2*a+b/2+c**3

In [118]:
my_function(3,6,8)

521.0

In [ ]:
Task

Create a function which takes input as the transaction amount

the function should return net payable under the following condition

if amount is less than 2000 - no discount
for any amount between 2000 and 5000 - 15% discount (2000 included but 5000 excluded)
for any amount more than or equal to 5000 - 20% discount

In [122]:
def net_payable(trans_amt):
    
    if trans_amt<2000:
        discount = 0
    
    elif trans_amt<5000:
        discount = trans_amt*.15
    
    else:
        discount = trans_amt*.20
    
    net_payable = trans_amt - discount

    return net_payable
    

In [123]:
net_payable(6000)

4800.0

In [125]:
6000 - 6000*.2

4800.0

In [126]:
def function():
    
    amt=float(input('Enter a number'))
    
    if amt<2000:
            discount = 0
    elif amt<5000: 
            discount = amt*.15
    else:
            discount=amt*.20
    return (amt-discount)

In [127]:
function()

Enter a number 6000


4800.0

In [ ]:
Non-keyword arguments(positional) and keyword arguments

In [128]:
def my_function(a,b,c):
    
    return 2*a+b/2+c**3

In [129]:
my_function(3,6,8)

521.0

In [130]:
my_function(8,6,3)

46.0

In [ ]:
In this way we need to take care of the positions of the arguments
if position changes output will also change

In [136]:
def my_function(a=0,b=0,c=0):
    
    '''
    This function takes 3 arguments. We used it for learning purposes
    
    '''
    return 2*a+b/2+c**3

In [132]:
my_function(a=3,b=6,c=8)

521.0

In [133]:
my_function(c=8,b=6,a=3)

521.0

In [135]:
my_function()

0.0

In [ ]:
args   -- non-keyword arguments
kwargs -- keyword arguments

In [ ]:
When we are not sure about the number of arguments

In [1]:
def add_numbers(*args):
    
    tot = 0
    
    for i in args:
        
        tot = tot + i
    
    return tot

In [2]:
add_numbers(23,34)

57

In [3]:
add_numbers(23,34,56)

113

In [4]:
def info(name, age, **kwargs):
    
    print(name, age, kwargs)
    

In [5]:
info('shubham', 40, designation = 'trainer')

shubham 40 {'designation': 'trainer'}


In [11]:
i = None

def pow(x,y):
    
    res = 1
    
    for i in range(y):
        
        res = res*x
        
    print(res)

In [7]:
pow(10,3)

1000


In [9]:
print(i)  # value of i is from outside the function

None


In [10]:
print(res)  # error: cannt access 'res' out of scope of function 'pow'

NameError: name 'res' is not defined

In [16]:
i = 10
res = 20
j = 30

# i, j and res are global variables

print('i before loop', i)
print('res before loop',res)

def pow(x,y):
    
    res = 1

# local variable is hiding the global variable(defined earlier) within the scope of this function

    for i in range(y):
        
        res = res*x
        
    print('res in loop', res) # i and res are as per values in pow
    print('j in pow', j) 

    
print('j after loop def', j) # j assined before pow is available

pow(10,3)

print('i after function call', i); print('j after function call',j); print('res after function call',res)

i before loop 10
res before loop 20
j after loop def 30
res in loop 1000
j in pow 30
i after function call 10
j after function call 30
res after function call 20


In [17]:
def func():
    
    global i
    
    i = 10
    print('i in function', i)


In [18]:
func()

i in function 10


In [19]:
print(i)

10


In [23]:
i = 10
res = 20
j = 30

# i, j and res are global variables

print('i before loop', i)
print('res before loop',res)

def pow(x,y):
    
    global res
    res = 1

# local variable is hiding the global variable(defined earlier) within the scope of this function

    for i in range(y):
        
        res = res*x
        
    print('res in loop', res) # i and res are as per values in pow
    print('j in pow', j) 

    
print('j after loop def', j) # j assined before pow is available

pow(10,3)

print('i after function call', i); print('j after function call',j); print('res after function call',res)

i before loop 10
res before loop 20
j after loop def 30
res in loop 1000
j in pow 30
i after function call 10
j after function call 30
res after function call 1000


#### One line if condition

In [20]:
var = 500

In [21]:
if var>100:
    print('value is more than 100')

value is more than 100


In [22]:
if var>100: print('value is more than 100')

value is more than 100


In [24]:
print('value is more than 100') if var > 100 else print('value less than or equal to 100')

value is more than 100


In [25]:
var = 60

In [26]:
print('value is more than 100') if var > 100 else print('value less than or equal to 100')

value less than or equal to 100


In [28]:
for l in ['a', 'b', 'c', 'd']:
    
    print(l)

a
b
c
d


In [29]:
for l in 'abcd':
    
    print(l)

a
b
c
d


In [32]:
for l in 'abcd':
    if l == 'b':
        break
    print(l)

a


In [33]:
for l in 'abcd':
    if l == 'b':
        continue
    print(l)

a
c
d


In [34]:
'a' in 'abcd'

True

In [35]:
'z' in 'abcd'

False

In [36]:
'z' not in 'abcd'

True

In [ ]:
Task

'Python' - print only the consonants

In [38]:
for l in 'Python':
    
    if l not in 'aeiou':
        
        print(l)

P
y
t
h
n


In [41]:
char = ''

for l in 'Python':
    
    if l not in 'aeiou':
        
        #print(l)
        
        char = char + l

In [42]:
char

'Pythn'

In [44]:
x='python'

for i in x:
    if i in 'aeiou':
        continue
    else:
        print(i)

p
y
t
h
n


In [46]:
for l in 'aeiou':
    
    if l == 'a' or l == 'e':
        continue
    print(l)

i
o
u


In [48]:
for i in 'python':
    
    if (i == 'a') or (i == 'e') or (i == 'i') or (i == 'o') or (i == 'u'):
        
        continue
        
    else:
        print(i) 

p
y
t
h
n


In [49]:
[i for i in 'Python' if i not in 'aeiou']

['P', 'y', 't', 'h', 'n']

In [50]:
for i, x in enumerate('Python'):
    
    print(i, x)

0 P
1 y
2 t
3 h
4 o
5 n


In [51]:
for i, x in enumerate('Python', start=1):
    
    print(i, x)

1 P
2 y
3 t
4 h
5 o
6 n


In [ ]:
Task:
    
Find list of employees joined betweeen 1995 and 2005

Each emp id is a numeric string where first 4 digits signigy the year of joining

In [52]:
empids = ['2017001', '2016001', '2017002', '1995091', '1996002', '199910','2003100', '2007301']

In [53]:
new_list = []

for index, item in enumerate(empids):

    if (int(empids[index][:4]) >= 1995) and (int(empids[index][:4]) <= 2005):
        
        new_list.append(empids[index])

In [54]:
new_list

['1995091', '1996002', '199910', '2003100']

In [55]:
s = {'zebra', 'elephant', 'penguine', 'python', 'serpant', 'viper'}

In [ ]:
create a list of animal names starting from 'p'

In [58]:
lst_animals = []

for animal in s:
    
    if animal[0] == 'p':
        
        lst_animals.append(animal)

In [59]:
lst_animals

['python', 'penguine']

In [56]:
name_age = {'a':40,'b':50,'c':30,'d':30,'e':40,'f':18,'g':15,'h':25}

In [ ]:
find those names where age is less than 30 years

In [66]:
name_age.items()

dict_items([('a', 40), ('b', 50), ('c', 30), ('d', 30), ('e', 40), ('f', 18), ('g', 15), ('h', 25)])

In [65]:
for name,age in name_age.items():
    if age<=30:
        print(name)

c
d
f
g
h


In [ ]:
create a dictionary of 100 items

the items are like

{101:'file1', 102:'file2', 103:'file3'........200:'file100'}

In [68]:
dict= {}

for key in range(101, 201):
    value = "file" + str(key - 100)
    dict[key] = value

In [70]:
print(dict)

{101: 'file1', 102: 'file2', 103: 'file3', 104: 'file4', 105: 'file5', 106: 'file6', 107: 'file7', 108: 'file8', 109: 'file9', 110: 'file10', 111: 'file11', 112: 'file12', 113: 'file13', 114: 'file14', 115: 'file15', 116: 'file16', 117: 'file17', 118: 'file18', 119: 'file19', 120: 'file20', 121: 'file21', 122: 'file22', 123: 'file23', 124: 'file24', 125: 'file25', 126: 'file26', 127: 'file27', 128: 'file28', 129: 'file29', 130: 'file30', 131: 'file31', 132: 'file32', 133: 'file33', 134: 'file34', 135: 'file35', 136: 'file36', 137: 'file37', 138: 'file38', 139: 'file39', 140: 'file40', 141: 'file41', 142: 'file42', 143: 'file43', 144: 'file44', 145: 'file45', 146: 'file46', 147: 'file47', 148: 'file48', 149: 'file49', 150: 'file50', 151: 'file51', 152: 'file52', 153: 'file53', 154: 'file54', 155: 'file55', 156: 'file56', 157: 'file57', 158: 'file58', 159: 'file59', 160: 'file60', 161: 'file61', 162: 'file62', 163: 'file63', 164: 'file64', 165: 'file65', 166: 'file66', 167: 'file67', 168

In [71]:
name_age = {}

count = 1

for key in range(101, 201):
    value = 'file' + str(count)
    name_age[key] = value
    count += 1
print(name_age)

{101: 'file1', 102: 'file2', 103: 'file3', 104: 'file4', 105: 'file5', 106: 'file6', 107: 'file7', 108: 'file8', 109: 'file9', 110: 'file10', 111: 'file11', 112: 'file12', 113: 'file13', 114: 'file14', 115: 'file15', 116: 'file16', 117: 'file17', 118: 'file18', 119: 'file19', 120: 'file20', 121: 'file21', 122: 'file22', 123: 'file23', 124: 'file24', 125: 'file25', 126: 'file26', 127: 'file27', 128: 'file28', 129: 'file29', 130: 'file30', 131: 'file31', 132: 'file32', 133: 'file33', 134: 'file34', 135: 'file35', 136: 'file36', 137: 'file37', 138: 'file38', 139: 'file39', 140: 'file40', 141: 'file41', 142: 'file42', 143: 'file43', 144: 'file44', 145: 'file45', 146: 'file46', 147: 'file47', 148: 'file48', 149: 'file49', 150: 'file50', 151: 'file51', 152: 'file52', 153: 'file53', 154: 'file54', 155: 'file55', 156: 'file56', 157: 'file57', 158: 'file58', 159: 'file59', 160: 'file60', 161: 'file61', 162: 'file62', 163: 'file63', 164: 'file64', 165: 'file65', 166: 'file66', 167: 'file67', 168

In [73]:
print({i:'file'+str(j) for i, j in zip(range(101, 201),range(1,101))})

{101: 'file1', 102: 'file2', 103: 'file3', 104: 'file4', 105: 'file5', 106: 'file6', 107: 'file7', 108: 'file8', 109: 'file9', 110: 'file10', 111: 'file11', 112: 'file12', 113: 'file13', 114: 'file14', 115: 'file15', 116: 'file16', 117: 'file17', 118: 'file18', 119: 'file19', 120: 'file20', 121: 'file21', 122: 'file22', 123: 'file23', 124: 'file24', 125: 'file25', 126: 'file26', 127: 'file27', 128: 'file28', 129: 'file29', 130: 'file30', 131: 'file31', 132: 'file32', 133: 'file33', 134: 'file34', 135: 'file35', 136: 'file36', 137: 'file37', 138: 'file38', 139: 'file39', 140: 'file40', 141: 'file41', 142: 'file42', 143: 'file43', 144: 'file44', 145: 'file45', 146: 'file46', 147: 'file47', 148: 'file48', 149: 'file49', 150: 'file50', 151: 'file51', 152: 'file52', 153: 'file53', 154: 'file54', 155: 'file55', 156: 'file56', 157: 'file57', 158: 'file58', 159: 'file59', 160: 'file60', 161: 'file61', 162: 'file62', 163: 'file63', 164: 'file64', 165: 'file65', 166: 'file66', 167: 'file67', 168

In [74]:
[emp for emp in empAll if emp not in grp1 and emp not in grp2]

['emp2', 'emp4', 'emp6']

In [76]:
lst = []
for i in empAll:
    if i in (grp1) or i in (grp2):
        continue
    else:
        print(i)
    lst.append(i)

emp2
emp4
emp6


In [77]:
empAll = ['emp1', 'emp2', 'emp3', 'emp4', 'emp5', 'emp6']
grp1 = ['emp1', 'emp3']
grp2 = ['emp22', 'emp1', 'emp5']


for i in empAll:
    if i in grp1 or i in grp2:
        empAll.remove(i)


print(empAll)

['emp2', 'emp4', 'emp6']


In [78]:
set(empAll) - set(grp1+grp2)

{'emp2', 'emp4', 'emp6'}

In [81]:
emp = []

for i in empAll:
    if i in grp1 or i in grp2:
        continue
    print(i)
    emp.append(i)
    
print(empAll)

emp2
emp4
emp6
['emp2', 'emp4', 'emp6']


In [82]:
emp

['emp2', 'emp4', 'emp6']

## Basic string functions

In [83]:
string = 'Python'

In [84]:
string[1:4:1]

'yth'

In [85]:
string.upper()

'PYTHON'

In [86]:
string.lower()

'python'

In [87]:
string.title()

'Python'

In [88]:
'sHuBham pAndey'.title()

'Shubham Pandey'

In [89]:
'_'.join('Python')

'P_y_t_h_o_n'

In [91]:
'_'.join(['23','45'])

'23_45'

In [ ]:
create a string as follows

'y ~ x1 + x2 + x3 +.......x200'

In [95]:
' + '.join(['x'+ str(i) for i in range(1,201)])

'x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x20 + x21 + x22 + x23 + x24 + x25 + x26 + x27 + x28 + x29 + x30 + x31 + x32 + x33 + x34 + x35 + x36 + x37 + x38 + x39 + x40 + x41 + x42 + x43 + x44 + x45 + x46 + x47 + x48 + x49 + x50 + x51 + x52 + x53 + x54 + x55 + x56 + x57 + x58 + x59 + x60 + x61 + x62 + x63 + x64 + x65 + x66 + x67 + x68 + x69 + x70 + x71 + x72 + x73 + x74 + x75 + x76 + x77 + x78 + x79 + x80 + x81 + x82 + x83 + x84 + x85 + x86 + x87 + x88 + x89 + x90 + x91 + x92 + x93 + x94 + x95 + x96 + x97 + x98 + x99 + x100 + x101 + x102 + x103 + x104 + x105 + x106 + x107 + x108 + x109 + x110 + x111 + x112 + x113 + x114 + x115 + x116 + x117 + x118 + x119 + x120 + x121 + x122 + x123 + x124 + x125 + x126 + x127 + x128 + x129 + x130 + x131 + x132 + x133 + x134 + x135 + x136 + x137 + x138 + x139 + x140 + x141 + x142 + x143 + x144 + x145 + x146 + x147 + x148 + x149 + x150 + x151 + x152 + x153 + x154 + x155 + x156 + x157 + x158 + x

In [96]:
'y ~ ' + ' + '.join(['x'+ str(i) for i in range(1,201)])

'y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10 + x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x20 + x21 + x22 + x23 + x24 + x25 + x26 + x27 + x28 + x29 + x30 + x31 + x32 + x33 + x34 + x35 + x36 + x37 + x38 + x39 + x40 + x41 + x42 + x43 + x44 + x45 + x46 + x47 + x48 + x49 + x50 + x51 + x52 + x53 + x54 + x55 + x56 + x57 + x58 + x59 + x60 + x61 + x62 + x63 + x64 + x65 + x66 + x67 + x68 + x69 + x70 + x71 + x72 + x73 + x74 + x75 + x76 + x77 + x78 + x79 + x80 + x81 + x82 + x83 + x84 + x85 + x86 + x87 + x88 + x89 + x90 + x91 + x92 + x93 + x94 + x95 + x96 + x97 + x98 + x99 + x100 + x101 + x102 + x103 + x104 + x105 + x106 + x107 + x108 + x109 + x110 + x111 + x112 + x113 + x114 + x115 + x116 + x117 + x118 + x119 + x120 + x121 + x122 + x123 + x124 + x125 + x126 + x127 + x128 + x129 + x130 + x131 + x132 + x133 + x134 + x135 + x136 + x137 + x138 + x139 + x140 + x141 + x142 + x143 + x144 + x145 + x146 + x147 + x148 + x149 + x150 + x151 + x152 + x153 + x154 + x155 + x156 + x157 + x158

In [97]:
txt = 'I love excel but python is much better tool for AI'

In [99]:
txt.split()

['I',
 'love',
 'excel',
 'but',
 'python',
 'is',
 'much',
 'better',
 'tool',
 'for',
 'AI']

In [100]:
txt = 'I_love_excel_but_python_is_much_better_tool_for_AI'

In [101]:
txt.split(sep='_')

['I',
 'love',
 'excel',
 'but',
 'python',
 'is',
 'much',
 'better',
 'tool',
 'for',
 'AI']

In [102]:
txt = 'I_love_excel; but_python_is_much_better_tool_for_AI, you know'

In [104]:
txt.split(sep='; | ,')

['I_love_excel; but_python_is_much_better_tool_for_AI, you know']

In [105]:
import re

In [107]:
re.split(';|,',txt)

['I_love_excel', ' but_python_is_much_better_tool_for_AI', ' you know']

In [109]:
txt.replace('_',' ')

'I love excel; but python is much better tool for AI, you know'

In [110]:
txt.replace('_',' ').replace(';',' ')

'I love excel  but python is much better tool for AI, you know'

In [111]:
txt.replace('_',' ').replace(';',' ').replace(',',' ')

'I love excel  but python is much better tool for AI  you know'

In [112]:
txt.find('AI')

49

In [114]:
txt = 'I love excel  but python is much better tool for AI, you know AI'

In [115]:
txt.find('AI')

49

In [116]:
txt.find('AI', 50)

62

In [ ]:
Task

Find all the numbers from 1-1000 that have a 3 in them

In [121]:
num_3 = []

for i in range(1001):
    
    if '3' in str(i):
        
        num_3.append(i)

In [123]:
print(num_3)

[3, 13, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 53, 63, 73, 83, 93, 103, 113, 123, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 143, 153, 163, 173, 183, 193, 203, 213, 223, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 243, 253, 263, 273, 283, 293, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 403, 413, 423, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 443, 453, 463, 473, 483, 493, 503, 513, 523, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 543, 553, 563, 573, 583, 593, 603, 613, 623, 630, 631, 632, 633, 634, 635,

In [124]:
len(num_3)

271

In [128]:
for i in (1,1001):
    
    z = str(i)
    
    if z.find('3') > 0:
        print(i)

In [135]:
lst_3within = []

for i in range(1,1001):
    
    z = str(i)
    
    if str(i).find('3') >= 0:
        lst_3within.append(i)

In [136]:
print(lst_3within)

[3, 13, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 53, 63, 73, 83, 93, 103, 113, 123, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 143, 153, 163, 173, 183, 193, 203, 213, 223, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 243, 253, 263, 273, 283, 293, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 403, 413, 423, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 443, 453, 463, 473, 483, 493, 503, 513, 523, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 543, 553, 563, 573, 583, 593, 603, 613, 623, 630, 631, 632, 633, 634, 635,

In [ ]:
Remove all the vowels in a string

In [140]:
text = 'My love Python'

In [141]:
for i in 'aeiou':
    
    text = text.lower().replace(i, '')
    
print(text)

my lv pythn


In [1]:
for i in range(1,10):  # outer loop
    
    for j in range(1,10): # inner loop
        
        k = i*j
        
        print(k, end = ' ')

1 2 3 4 5 6 7 8 9 2 4 6 8 10 12 14 16 18 3 6 9 12 15 18 21 24 27 4 8 12 16 20 24 28 32 36 5 10 15 20 25 30 35 40 45 6 12 18 24 30 36 42 48 54 7 14 21 28 35 42 49 56 63 8 16 24 32 40 48 56 64 72 9 18 27 36 45 54 63 72 81 

In [ ]:
First iteration of outer loop

i = 1

--- inner loop will go through the complete cycle - it will execute completely

first iteration of inner loop

j = 1
i = 1

k = 1*1 = 1

second iteration of inner loop

j = 2
i = 1

k = 1*2 = 2

In [4]:
# While loop

var = 10

while var > 0:
    
    var = var - 1
    
    print(var)

9
8
7
6
5
4
3
2
1
0


In [5]:
var = 10

while var > 0:
    
    var = var - 1
    
    if var == 5:
        
        continue
    
    print(var)

9
8
7
6
4
3
2
1
0


In [6]:
var = 10

while var > 0:
    
    var = var - 1
    
    if var == 5:
        
        break
    
    print(var)

9
8
7
6


## Numpy array

In [7]:
import numpy

In [9]:
height = [175, 180, 165]
weight = [75, 80, 68]
sales_quarter_2020 = [20,30,40,50]
sales_quarter_2021 = [45,35,34,21]

In [10]:
numpy.array(height)

array([175, 180, 165])

In [11]:
height_array = numpy.array(height)

In [12]:
numpy.array(weight)

array([75, 80, 68])

In [13]:
weight_array = numpy.array(weight)

In [ ]:
Calculate BMI

In [14]:
weight_array/pow(height_array/100,2)

array([24.48979592, 24.69135802, 24.97704316])

In [16]:
import numpy as np

In [17]:
np.array(height)

array([175, 180, 165])

In [18]:
from numpy import array,sum

In [20]:
np.array(height)  # 1 D array

array([175, 180, 165])

In [22]:
np.array([[2,4,7],[8,3,9]])  # 2 D array

array([[2, 4, 7],
       [8, 3, 9]])

In [23]:
np.array([[2,4,7],[8,3,9],[12,1,8]])  # 2 D array

array([[ 2,  4,  7],
       [ 8,  3,  9],
       [12,  1,  8]])

In [24]:
arr_2d = np.array([[2,4,7],[8,3,9],[12,1,8]])  # 2 D array

In [25]:
arr_2d

array([[ 2,  4,  7],
       [ 8,  3,  9],
       [12,  1,  8]])

In [37]:
arr_2d.shape

(3, 3)

In [26]:
my_array = np.array(['Shubham', True, 40, 25])

In [27]:
my_array

array(['Shubham', 'True', '40', '25'], dtype='<U21')

In [28]:
my_array[0]

'Shubham'

In [29]:
my_array[0:3]

array(['Shubham', 'True', '40'], dtype='<U21')

In [30]:
my_array[0] = 'Vishal'

In [31]:
my_array

array(['Vishal', 'True', '40', '25'], dtype='<U21')

In [ ]:
Learning

Array are

homogenous
ordered
mutable
n-dimensional

In [32]:
array_3d = np.array([[[2,5,10],[12,14,16],[10,19,18],[10,9,7],[9,12,17],[0,8,0]]])

In [33]:
array_3d

array([[[ 2,  5, 10],
        [12, 14, 16],
        [10, 19, 18],
        [10,  9,  7],
        [ 9, 12, 17],
        [ 0,  8,  0]]])

In [36]:
array_3d.shape

(1, 6, 3)

In [38]:
array_3d = np.array([[[2,5,10],[12,14,16],[10,19,18]],[[10,9,7],[9,12,17],[0,8,0]]])

In [39]:
array_3d

array([[[ 2,  5, 10],
        [12, 14, 16],
        [10, 19, 18]],

       [[10,  9,  7],
        [ 9, 12, 17],
        [ 0,  8,  0]]])

In [40]:
array_3d.shape

(2, 3, 3)

In [34]:
np.array([[True,False,'Array'],[40,20,30]])

array([['True', 'False', 'Array'],
       ['40', '20', '30']], dtype='<U21')

In [35]:
np.array([[True,False,2],[40,20,30]])

array([[ 1,  0,  2],
       [40, 20, 30]])

In [41]:
arr_2d = np.array([[2,4,7],[8,3,9],[12,1,8]])

In [42]:
arr_2d

array([[ 2,  4,  7],
       [ 8,  3,  9],
       [12,  1,  8]])

In [43]:
arr_2d.sum()

54

In [44]:
arr_2d.sum(axis=0)

array([22,  8, 24])

In [45]:
arr_2d.sum(axis=1)

array([13, 20, 21])

In [46]:
arr_2d.mean(axis=0)

array([7.33333333, 2.66666667, 8.        ])

In [47]:
arr_2d.mean(axis=1)

array([4.33333333, 6.66666667, 7.        ])

### Subsetting/Slicing

In [48]:
arr_2d

array([[ 2,  4,  7],
       [ 8,  3,  9],
       [12,  1,  8]])

In [49]:
arr_2d[1,2]

9

In [50]:
arr_2d[1:,2]

array([9, 8])

### subsetting based on conditions

In [51]:
arr1 = np.array([23,26,76,20,15,10,12])

In [ ]:
Items that are less than 20?

In [52]:
arr1<20

array([False, False, False, False,  True,  True,  True])

In [53]:
arr1[arr1<20]

array([15, 10, 12])

In [ ]:
Items which are more than 10 but less than 20

In [55]:
(arr1<20) and (arr1>10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
(arr1<20) & (arr1>10)

array([False, False, False, False,  True, False,  True])

In [57]:
(arr1<20)

array([False, False, False, False,  True,  True,  True])

In [58]:
(arr1>10)

array([ True,  True,  True,  True,  True, False,  True])

In [59]:
arr1[(arr1<20) & (arr1>10)]

array([15, 12])

#### Distance between 2 points

In [60]:
pt1 = np.array([1,5])
pt2 = np.array([4,3])

In [61]:
pt1 - pt2

array([-3,  2])

In [62]:
np.square(pt1 - pt2)

array([9, 4])

In [63]:
np.sum(np.square(pt1 - pt2))

13

In [64]:
np.sqrt(np.sum(np.square(pt1 - pt2)))

3.605551275463989

In [65]:
np.linalg.norm(pt1 - pt2)

3.605551275463989

In [66]:
np.array([[2,3],[4,5]]) - np.array([[4,5],[8,7]]) 

array([[-2, -2],
       [-4, -2]])

In [67]:
np.array([[2,3],[4,5]]) + np.array([[4,5],[8,7]]) 

array([[ 6,  8],
       [12, 12]])

In [69]:
np.dot(np.array([[2,3],[1,0]]),np.array([[1,2,3],[0,4,3]]))

array([[ 2, 16, 15],
       [ 1,  2,  3]])

In [70]:
mtrx1 = np.dot(np.array([[2,3],[1,0]]),np.array([[1,2,3],[0,4,3]]))

In [72]:
mtrx1

array([[ 2, 16, 15],
       [ 1,  2,  3]])

In [71]:
np.transpose(mtrx1)

array([[ 2,  1],
       [16,  2],
       [15,  3]])

In [73]:
arr_2d = np.array([[2,4,7],[8,3,9],[12,1,8]])

In [74]:
arr_2d

array([[ 2,  4,  7],
       [ 8,  3,  9],
       [12,  1,  8]])

In [75]:
np.linalg.inv(arr_2d)

array([[ 1.5, -2.5,  1.5],
       [ 4.4, -6.8,  3.8],
       [-2.8,  4.6, -2.6]])

In [76]:
np.dot(arr_2d, np.linalg.inv(arr_2d))

array([[ 1.00000000e+00,  2.66453526e-15,  1.33226763e-15],
       [ 1.33226763e-15,  1.00000000e+00, -1.33226763e-15],
       [-3.55271368e-15,  0.00000000e+00,  1.00000000e+00]])

In [77]:
np.trace(arr_2d)

13

## Pandas series and dataframe

In [78]:
import pandas as pd

In [80]:
name_age = pd.Series({'a':30,'b':40,'c':15,'d':50,'e':25,'f':20})

In [81]:
type(name_age)

pandas.core.series.Series

In [ ]:
Series: One-dimensional ndarray with axis labels (including time series).

In [82]:
name_age

a    30
b    40
c    15
d    50
e    25
f    20
dtype: int64

In [83]:
name_age.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [84]:
name_age.values

array([30, 40, 15, 50, 25, 20])

In [85]:
name_age[0]

30

In [86]:
name_age['a']

30

In [87]:
name_age[1:6:2]

b    40
d    50
f    20
dtype: int64

In [88]:
name_age<20

a    False
b    False
c     True
d    False
e    False
f    False
dtype: bool

In [89]:
name_age[name_age<20]

c    15
dtype: int64

In [90]:
name_age.mean()

30.0

In [91]:
name_age.median()

27.5

In [92]:
name_age.describe()

count     6.000000
mean     30.000000
std      13.038405
min      15.000000
25%      21.250000
50%      27.500000
75%      37.500000
max      50.000000
dtype: float64

In [93]:
name_age = pd.Series({'a':30,'b':40,'c':15,'d':50,'e':25,'f':20, 'g':50,'h':30,'i':50})

In [94]:
name_age

a    30
b    40
c    15
d    50
e    25
f    20
g    50
h    30
i    50
dtype: int64

In [95]:
name_age.value_counts()

50    3
30    2
40    1
15    1
25    1
20    1
dtype: int64

In [96]:
name_age.value_counts(ascending=True)

40    1
15    1
25    1
20    1
30    2
50    3
dtype: int64

In [97]:
name_age.value_counts(normalize=True)

50    0.333333
30    0.222222
40    0.111111
15    0.111111
25    0.111111
20    0.111111
dtype: float64

In [98]:
(name_age.value_counts(normalize=True))*100

50    33.333333
30    22.222222
40    11.111111
15    11.111111
25    11.111111
20    11.111111
dtype: float64

In [100]:
round((name_age.value_counts(normalize=True))*100, 2)

50    33.33
30    22.22
40    11.11
15    11.11
25    11.11
20    11.11
dtype: float64

### Dataframe

In [135]:
df = pd.DataFrame({'col1':['item'+str(i) for i in range(1,6)], 'col2': [23, 24, 28, 30, 32], 'col3': [98,92,94,91,90], 'col4': ['a', 'b', 'b', 'a', 'a']})

In [136]:
df

col1  col2  col3 col4
0  item1    23    98    a
1  item2    24    92    b
2  item3    28    94    b
3  item4    30    91    a
4  item5    32    90    a

In [137]:
type(df)

pandas.core.frame.DataFrame

In [138]:
df.col1

0    item1
1    item2
2    item3
3    item4
4    item5
Name: col1, dtype: object

In [139]:
type(df.col1)

pandas.core.series.Series

In [140]:
df['col1']

0    item1
1    item2
2    item3
3    item4
4    item5
Name: col1, dtype: object

In [141]:
type(df['col1'])

pandas.core.series.Series

In [142]:
df['col1']

0    item1
1    item2
2    item3
3    item4
4    item5
Name: col1, dtype: object

In [144]:
df[['col1']]  # dataframe

col1
0  item1
1  item2
2  item3
3  item4
4  item5

In [110]:
df.col4.value_counts()

a    3
b    2
Name: col4, dtype: int64

In [113]:
df.col2.mean()

27.4

In [114]:
df.col2.median()

28.0

In [115]:
df.col2.describe()

count     5.000000
mean     27.400000
std       3.847077
min      23.000000
25%      24.000000
50%      28.000000
75%      30.000000
max      32.000000
Name: col2, dtype: float64

In [117]:
df = pd.DataFrame({'col1':['item'+str(i) for i in range(1,6)], 'col2': [23, 24, 28, 30, 32], 'col3': [98,92,94,91,90], 'col4': ['a', 'b', 'b', 'a', 'a']}, index = ['ind' + str(i) for i in range(5)])

In [118]:
df

col1  col2  col3 col4
ind0  item1    23    98    a
ind1  item2    24    92    b
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

In [119]:
df.index

Index(['ind0', 'ind1', 'ind2', 'ind3', 'ind4'], dtype='object')

In [120]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [121]:
df.shape

(5, 4)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ind0 to ind4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    5 non-null      object
 1   col2    5 non-null      int64 
 2   col3    5 non-null      int64 
 3   col4    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 200.0+ bytes


In [123]:
df.dtypes

col1    object
col2     int64
col3     int64
col4    object
dtype: object

In [124]:
df.describe()

col2       col3
count   5.000000   5.000000
mean   27.400000  93.000000
std     3.847077   3.162278
min    23.000000  90.000000
25%    24.000000  91.000000
50%    28.000000  92.000000
75%    30.000000  94.000000
max    32.000000  98.000000

In [145]:
df

col1  col2  col3 col4
0  item1    23    98    a
1  item2    24    92    b
2  item3    28    94    b
3  item4    30    91    a
4  item5    32    90    a

In [146]:
df.dtypes

col1    object
col2     int64
col3     int64
col4    object
dtype: object

In [125]:
df.describe(include='O')

col1 col4
count       5    5
unique      5    2
top     item1    a
freq        1    3

In [126]:
df.describe(include='object')

col1 col4
count       5    5
unique      5    2
top     item1    a
freq        1    3

In [129]:
df.head()  # by default first 5 records are populated

col1  col2  col3 col4
ind0  item1    23    98    a
ind1  item2    24    92    b
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

In [131]:
df.tail() # by default last 5 records are populated

col1  col2  col3 col4
ind0  item1    23    98    a
ind1  item2    24    92    b
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

In [132]:
df.head(2)  # by default first 5 records are populated

col1  col2  col3 col4
ind0  item1    23    98    a
ind1  item2    24    92    b

In [133]:
df.tail(3)  # by default first 5 records are populated

col1  col2  col3 col4
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

### Subsetting a dataframe

In [148]:
df = pd.DataFrame({'col1':['item'+str(i) for i in range(1,6)], 'col2': [23, 24, 28, 30, 32], 'col3': [98,92,94,91,90], 'col4': ['a', 'b', 'b', 'a', 'a']}, index = ['ind' + str(i) for i in range(5)])

In [149]:
df

col1  col2  col3 col4
ind0  item1    23    98    a
ind1  item2    24    92    b
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

In [ ]:
loc - to subset based on row and column labels
iloc - to subset based on row and column integer index values

In [150]:
df.loc[['ind1', 'ind4'],['col1', 'col3']]

col1  col3
ind1  item2    92
ind4  item5    90

In [151]:
df.iloc[[1,4],[0,2]]

col1  col3
ind1  item2    92
ind4  item5    90

In [152]:
df.iloc[[1,4],:]

col1  col2  col3 col4
ind1  item2    24    92    b
ind4  item5    32    90    a

In [153]:
df.iloc[:,[0,2]]

col1  col3
ind0  item1    98
ind1  item2    92
ind2  item3    94
ind3  item4    91
ind4  item5    90

In [155]:
df.iloc[[1,4],1:]

col2  col3 col4
ind1    24    92    b
ind4    32    90    a

In [156]:
df.iloc[[1,4],:3]

col1  col2  col3
ind1  item2    24    92
ind4  item5    32    90

In [158]:
df.loc[df.col2>25,['col1', 'col3']]

col1  col3
ind2  item3    94
ind3  item4    91
ind4  item5    90

In [159]:
df.col2

ind0    23
ind1    24
ind2    28
ind3    30
ind4    32
Name: col2, dtype: int64

In [160]:
df.col2>25

ind0    False
ind1    False
ind2     True
ind3     True
ind4     True
Name: col2, dtype: bool

In [161]:
df.col2[df.col2>25]

ind2    28
ind3    30
ind4    32
Name: col2, dtype: int64

In [162]:
df.loc[df.col2>25,:]

col1  col2  col3 col4
ind2  item3    28    94    b
ind3  item4    30    91    a
ind4  item5    32    90    a

In [163]:
# subset df for those records where col2 has values more than 25, and col4 values should be 'a' only

df.loc[(df.col2>25) & (df.col4=='a'),:]

col1  col2  col3 col4
ind3  item4    30    91    a
ind4  item5    32    90    a